### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by dotfig** [Samantha-Mcguigan/newsAnalysis#1]
After class today, @ajnewton1 , @Samantha-Mcguigan, and @jonhoranic met with @RJP43 and me (@ebeshero), to discuss what to do next. @gretchenuhrinek was notably absent.

- [x] @jonhoranic will produce some basic XML markup on the four articles posted here so there's a common structural approach to all the documents, and post the files to this GitHub repo so everyone can pull them in.

- [x]  Once he's done that everyone should read these together in XML and think about the markup strategy. Returning to first principles, from your team's initial proposal post, consider your strategy for markup:

Possible things that could be marked up in the articles may be:

adjective and adverb use outside of direct quotations, and whether or not these words typically register a positive or negative emotion
sources and source credibility
use of statistics in the articles
age, gender, sex, and race of speakers, subjects, and journalists
Ideally, this markup would help reveal the integrity of news organizations and could perhaps be used as a sort of "truth finder" or something.

- [x] Next week's meeting should be about

- defining your markup strategy by working out your Relax NG schema.

- what other news topics you want to investigate in common: @ajnewton1 and I had an idea for scraping related news articles on the same topics that might bring in larger quantities, but we'll talk about that again next week.

Right now, the markup strategy should come first, together with refining your selection principle (what kinds of articles do you want to process in [X] way?)

Just a copy and paste from what @ebeshero posted in the previous repository

**Comment by dotfig** [comment]
@ajnewton1 @Samantha-Mcguigan
Quick update guys, the weekend had some technical hiccups here at home with the ever wonderful Comcast. It did not slow me down when it came to accessing things and starting to code, what did slow me down was helping the family set up the new TV's and Comcast boxes, so it has been a bit hectic with the house half dismantled.

My apologies on having to delay, but hopefully I can have a mark up by Monday night or sometime mid-Tuesday at the latest.

Just a copy and paste from what @jonhoranic posted in the previous repository
