### ISSUE TITLE
Tasks 4/12

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [Samantha-Mcguigan/newsAnalysis#8]
# Tasks for Friday Presentation in Oakland  
Be sure to check off tasks as you complete them so others know if ready to move on to next task of data visualizations. 

@jonhoranic
- [x] push womensMarch_NPR article
- [x]  get creative commons license on site
- [x] Change tab/pages from news topics to News Sources with News Titles/Topics as sub-headings
Each News Source page should include network graph, explanation of preconceived idea of news source, conclusions based on network and graphs
- [x] Add Analysis tab/page
- [x] complete womensMarch `<quote>` markup

@Samantha-Mcguigan 
- [x] change schema to add `@sex `and `@pol` to `<quote>` tag with 
`@sex`  values of `m|f|u|t`
`@pol` values of `dem|rep|u_rep|u_dem`
- [x] complete electionResults `<quote>` markup
 articles  
    
@ajnewton1 
- [x] complete trumpTaxes, travelBan, syrianBombings `<quote>` markup
- [x] once others have completed their assigned `<quote>` markup, add articles to eXide

**Comment by RJP43** [comment]
# Visualization Ideas

1. Bar Graph Comparing Number of Gendered Quotes used by Each News Source (Analysis Tab - with explanation)
2. Bar Graph Comparing Number of Politically Charged Quotes used by Each News Source (Analysis Tab - with explanation)
3. Four Cytoscape Networks of `<emo>` language per News Sources (includes all articles from a single News Source for each network) These will be on tab/page for each News Source

**Comment by Samantha-Mcguigan** [comment]
I can't push the changes to the schema, I'm getting a merge conflict but it won't let me pull anything in either. Should I just add the `@sex `and `@pol` attributes to the articles and worry about pushing them later?

**Comment by RJP43** [comment]
Are you still on campus?

**Comment by RJP43** [comment]
@Samantha-Mcguigan and I resolved this merge conflict. So basically what happened was Sam did not realize Aaron did work on his files before she attempted to add and commit her changes to the schema. So when she went to commit git said there was an error because the remote origin had changes she didn't have locally. To fix this we used the command `git rebase origin/master` followed by `git push` and then all was good again in the universe :)

@ajnewton1 @Samantha-Mcguigan @jonhoranic Moral of the story: be sure to always pull first!

**Comment by Samantha-Mcguigan** [comment]
Schema and electionResults articles are updated

**Comment by dotfig** [comment]
trumpTaxes, travelBan, and syrianBombings are all marked up and completed

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 Fixed my GitHub situation, something was going haywire with my working library and local file management. I reset it, had two merge conflicts, and I am **ASSUMING** that nothing has been pushed that would set us back since I cleared those old pushes that would have been "old copies" of our current files. I **HIGHLY RECOMMEND** you two double check and see if I have not broken anything, my apologies for any inconveniences and for not noticing this issue sooner.

**Comment by dotfig** [comment]
@jonhoranic It looks like everything is safe and sound. The only thing I would recommend would be to add the ``sex="" pol=""`` attributes to your ``<quote>`` elements in the womensMarch_NPR file.

**Comment by jonhoranic** [comment]
@ajnewton1 Good to hear, I am working on the website files as we speak and should be able to have that prepared for review before we put it up on the server. Can I ask you and @Samantha-Mcguigan to produce little introductory bios for the about page? Take a look at the other student projects for a roundabout model and just post them here, I'll will work on getting that presentable. We do not require photographs, but if either of you think that is something needed in the bio then we can manage. Let me know what you think.

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 The women's march articles are up, and I am still working on the website files. We can start developing visualizations now, but word of warning, check the files one last time before we upload them to the Exist Database because any changes we push to the GitHub here will NOT carry over unless we re-upload them to the Exist-DB constantly. I will ping in again when I have working web files.

**Comment by dotfig** [comment]
@jonhoranic @Samantha-Mcguigan The articles are in eXide. Am I supposed to put the schema in there as well?

**Comment by RJP43** [comment]
@ajnewton1 No, you just want the files in eXide that you want to query.

**Comment by RJP43** [comment]
Since @jonhoranic is working on site files perhaps divide the visualizations up among @Samantha-Mcguigan and @ajnewton1 Who is more comfortable with Cytoscape versus a SVG bar graph? First step for either visualization will be to create a query grabbing the parts of the markup you are interested in graphing/networking. Be sure to be saving in your indiv. eXide folders so as you have questions we can view your query and assist.

**Comment by Samantha-Mcguigan** [comment]
I'll do cytoscape

**Comment by RJP43** [comment]
@Samantha-Mcguigan see my notes above where I transcribed a bit of what we talked about as a group and what I discussed with Jon after class regarding the Cytoscape networks. @jonhoranic and I discussed using a Cytoscape graph for each news source but certainly if you have a different idea in mind go with it!

**Comment by dotfig** [comment]
I will do a bar graph showing the amount of males and females that are referenced

**Comment by Samantha-Mcguigan** [comment]
@RJP43 @ajnewton1 @jonhoranic I'm not sure exactly what you all want for the network? I know you mentioned `emo` tags but how do we want to use them? and what do I want to get for the edge? Also, you mentioned doing one for each of the news sources but they are not organized that way in eXide, they are in groups by topic. Can I still do it my news source then?

**Comment by jonhoranic** [comment]
I have **finally** gotten a rough homepage and format style based off of what @ajnewton1 had previously. I am going to now quickly finalize the new pages and then locally test/troubleshoot for a bit to make sure everything links properly before pushing and getting them onto the server.

**Comment by RJP43** [comment]
@Samantha-Mcguigan... I can't access my computer right this moment... are all of the files (whether in a sub-folder or not) sitting within a single folder?

If so, you can drop to the main folder and get only articles with the source ref for each specific news source.

**Comment by RJP43** [comment]
I mean the `<siteInfo> @ref`

**Comment by Samantha-Mcguigan** [comment]
@RJP43 oh right that makes a lot of sense! Also I was thinking I could also do a bar graph on the emo tags used per source instead? I think that makes more sense for us but if you want a network graph I can still do that I just don't know what you all wanted

**Comment by RJP43** [comment]
@Samantha-Mcguigan you can do as you wish since it is your project. 

Let me further explain the networks @jonhoranic and I discussed to see if it seems worth doing in general (maybe not for tomorrow however). 

Since the purpose of the project is to determine how certain news sources portray certain events differently by the emotional language and number of politically charged quotes, I suggested it might make sense to have each news source tab/page introduce a network that displays the variety of emo words from all of the articles gathered for each source along with a conclusive paragraph describing if the network goes with or against the perceived idea of that news source (ie. Fox is considered republican/conservative).

To do this, you would need a network for each news source. The central node would be the news source (BBC, NPR, etc.), the edges would be the article topics, and the target nodes would be the emo word. These networks would be kind of similar to the ones on my Nelson site where there is a single source node and a star burst of target nodes. You could add a target node attribute by grabbing the emo words part of speech.

Does this make any sense? Do you see how these networks could reveal the language of each news source pending on the article topic?

**Comment by RJP43** [comment]
*make ... Sorry not at my computer.

**Comment by Samantha-Mcguigan** [comment]
Yes that all makes sense! Thank you for your help!

**Comment by RJP43** [comment]
@Samantha-Mcguigan of course, no problem! ALSO, @jonhoranic please correct me if I've misrepresented the ideas we were bouncing around after class on Wednesday.

**Comment by Samantha-Mcguigan** [comment]
I am trying to grab all the CNN articles and I have:
```
declare variable $articles := collection('/db/newsAnalysis/');
declare variable $articleFiles := $articles/*;
declare variable $CNN := $articleFiles//siteInfo[@ref="CNN"]
```
but its just grabbing the siteInfo elements in these articles instead of the whole article? How do I fix that?

**Comment by dotfig** [comment]
@Samantha-Mcguigan go to my database and look at what I have. It was like that for me for a little. Make sure there is no ``declare default element namespace "http://www.w3.org/2000/svg";`` on the top of your code.

**Comment by RJP43** [comment]
@Samantha-Mcguigan notice where you are stopping.

You are stopping on the siteInfo elements  **that have** the CNN ref but not actually on the ref.

**Comment by RJP43** [comment]
@Samantha-Mcguigan Oh also ... if you want to grab the whole article you might instead grab articles and even the news topics by their base-uri pieces.

**Comment by RJP43** [comment]
That is if the articles are named as they are here in GitHub with the news topic and source separated by the underscore.

**Comment by RJP43** [comment]
While the source nodes are the news sources that doesn't necessarily mean you want your for-loop to run through the sources ... makes more sense to grab **for each** emo word the news source, topic, and part of speech associated.

Thoughts?

**Comment by RJP43** [comment]
@Samantha-Mcguigan

**Comment by Samantha-Mcguigan** [comment]
I'm confused hold on

**Comment by RJP43** [comment]
@ajnewton1 @Samantha-Mcguigan I would also say that even if you just get the queries completed tonight that would be enough to explain in tomorrow's brief presentations the end goal.

**Comment by dotfig** [comment]
Mine is being a little weird. I am trying to write and SVG file in eXide and its being stupid. When I go to view it in the browser it is saying, "This XML file does not appear to have any style information associated with it. The document tree is shown below."

**Comment by RJP43** [comment]
@Samantha-Mcguigan okay, sorry if I've confused things. You might be doing things a different, better way. I was just thinking out loud what might work.

**Comment by Samantha-Mcguigan** [comment]
I though I needed a different network graph for each source so I still need to get all the articles based on what source they are from first right?

**Comment by ebeshero** [comment]
@ajnewton1 Check if you've applied the SVG namespace in your XQuery!

**Comment by dotfig** [comment]
Ahhh thanks @ebeshero ! I think thats exactly what I told @Samantha-Mcguigan not to use. Whoops

**Comment by RJP43** [comment]
@Samantha-Mcguigan  since you are creating the input for Cytoscape my way would be making a master file  (of which can be sorted by source node using a where stmt) that would have all of the news sources and articles of which you then could cut and paste into separate files the different news sources so in the end would have 4 separate files to input individually... there are certainly other ways of doing this where you are only looking into the certain news source files and then looping so each query gets its own particular news source data.

**Comment by dotfig** [comment]
when I put the ``declare default element namespace "http://www.w3.org/2000/svg";`` in my code and run it, all of my values are 0 and I don't know why. When I take it out of my code and run it, all my values are what they should be.

**Comment by ebeshero** [comment]
@ajnewton1 Aha! This is a tough spot because your input XML is in no namespace, so you don't have anything to call it. Try this: DON'T declare a default namespace, but just use the other namespace line that requires a prefix, and give the SVG a prefix (as in svg:). You'll have to prefix all the SVG elements in your XQuery script, but I think that'll work!

**Comment by RJP43** [comment]
Also, welcome to the "it is always a name space issue" club ...  haha ... one of us 🙌

**Comment by Samantha-Mcguigan** [comment]
One of us. One of us. One of us. Also figured out how to grab all the full articles based on their source! Small victories!

**Comment by RJP43** [comment]
@Samantha-Mcguigan HUZZAH!

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 Hey! Web files coming in shortly! I left comment tags for where we can place svg and note our "work in progress areas" that need more immediate attention. I am going to push them now, I will then put them up on the server client, AND THEN I will rest up for tomorrow's presentation. If something seems off, make the changes needed!

**Comment by dotfig** [comment]
@Samantha-Mcguigan @jonhoranic I just finished my svg file. where shall I put it?

**Comment by jonhoranic** [comment]
@ajnewton1 Nest that svg file in the same file as the web files, when we call on it in the html it should pop into the site. The files are in the repo now, if you know where you are gonna place it open up the page and tinker around with it to see how it sits. I can hold off uploading to the server if we are going to be making changes. Sadly I think I am nodding off at my desk, is there anything pressing that I am missing???

**Comment by dotfig** [comment]
@jonhoranic I think we are all good. I will post my svg file into the Website folder and name it bar.svg

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 Aye aye, good work guys, see you both tomorrow!

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic Hey John I thought you might have some insight on this, I am trying to make a network in eXide and I am working in the edge which @RJP43 said she discussed with you as being the article topic. My only problem is that the topic is not in a tag inside the xml documents, its only in the document title. Is it possible for me to get the edge from that?

**Comment by Samantha-Mcguigan** [comment]
I think for now I might just make the edge the same as the source (CNN, FOX, NPR, BBC)

**Comment by RJP43** [comment]
@Samantha-Mcguigan you could tokenize base-uri... unless this is also encoded somewhere in the article where it might be easier to grab

**Comment by Samantha-Mcguigan** [comment]
@RJP43 Oh wow thats fancy, okay I will try that

**Comment by dotfig** [comment]
It looks like there is a little bit of a hiccup on the webpage. Im not sure if I should try to mess with it or not or should we just leave it be?

**Comment by Samantha-Mcguigan** [comment]
I figured out how to use tokenize and base-uri to get the article topics but I can't figure out how to walk back up the tree from the emo tags to get the title of the article

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Look all the way up the `ancestor::` axis to the root node of your file, and then look down from there for the title.

**Comment by Samantha-Mcguigan** [comment]
the root node of all the files is just `<article>` though.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Do you have a title coded as a descendant of the root node? Then look down the tree from the root node for the title. XPath lets you look up the ancestor axis and then look down the descendant axis from there.

**Comment by Samantha-Mcguigan** [comment]
wait hold on I think I might have figured it out

**Comment by Samantha-Mcguigan** [comment]
So this is what I'm doing for the edge:
```
let $emoTags := //article//emo/text()
for $e in $emoTags        
let $edge :=
    if (//article//emo[.=$e])
        then (//article//emo[.=$e]/ancestor::article/tokenize(base-uri(), '/')[4])
        else (//article//emo/text())
```
but I'm getting too many results. Any ideas?

**Comment by Samantha-Mcguigan** [comment]
I have: 
```
xquery version "3.0";
let $articles := collection('/db/newsAnalysis/')
let $articleFiles := $articles/*
let $source := $articleFiles//siteInfo//@ref
let $distinctSources := distinct-values($source)
let $emoTags := $articleFiles//emo/text()
for $s in $distinctSources
let $emos :=
        if (//article//siteInfo/@ref[. = $s])
                then (//article[descendant::siteInfo[@ref[.=$s]]]//emo/text())
        else (//article//emo/text())

for $e in $emoTags
      let $edgeType:=
        if ($e)
              then ($e/ancestor::article[descendant::emo[.=$e]]/tokenize(base-uri(), '/')[4])
        else "other"         
        
        
        for $emo in $emos
 return
         concat($s, "&#x9;", $edgeType, "&#x9;",$emo)
```
I'm getting 77,000 + results and I don't know why

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Sorry, I'm just seeing this. Do your results make sense, line by line? or are they missing  something/ don't always line up? 

I'm not sure I understand what you're trying to catch in your first if() then else statement. When *wouldn't* the siteInfo `@ref` = $s? (Or what is the distinction you're trying to make here between one condition and the rest? 
Anyway, I know you don't need parentheses around the then and  else statements.

**Comment by Samantha-Mcguigan** [comment]
I have this now:
```
xquery version "3.0";
let $articles := collection('/db/newsAnalysis/')
let $articleFiles := $articles/*
let $source := $articleFiles//siteInfo//@ref
let $distinctSources := distinct-values($source)
for $s in $distinctSources
let $emos :=
        if (//article//siteInfo/@ref[. = $s])
                then (//article[descendant::siteInfo[@ref[.=$s]]]//emo)
        else "other"
        
let $edge:=
        if (//article//siteInfo/@ref[. = $s]//emo)
              then (//article//siteInfo/@ref[. = $s]//emo/ancestor::article/tokenize(base-uri(), '/')[4])
        else "other"         
        
        
        for $emo in $emos
 return
         concat($s, "&#x9;", $edge, "&#x9;",$emo)
```
the only reason I have an else statement is because you have to have it. Do I even need to do an if then else statement ? I thought thats just what you had to do to make a network graph

**Comment by Samantha-Mcguigan** [comment]
I am getting the right number of results and the central and target nodes are right but the edges are all giving me "other"

**Comment by ebeshero** [comment]
@Samantha-Mcguigan No, you don't have to have it, and you don't want it if it isn't really distinguishing one kind of node from another. The point of the If / then /else is only when you need to use them to distinguish one type of node from another.  I'm not really clear on what you're trying to distinguish, and maybe you really don't need the if condition?

In our homework assignment we used `if() then else` to distinguish whether nodes came from a particular level of the Decameron. But your text data isn't so complicated, so I don't think you need this!

**Comment by Samantha-Mcguigan** [comment]
I think I still need it because the target mode is an emo tag based on what is inside the ref attribute on the siteInfo node higher up in the document but I'm not really sure? Anyway I have to give up for the night so I don't fall asleep driving everyone to Pittsburgh in a few hours

**Comment by dotfig** [comment]
In order to see the bar.svg file better, just click on it and it will open a new window

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I think we figured this out today, right?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Just a quick note--I think we figured out the network analysis data issue today, right?

**Comment by dotfig** [comment]
I also finished the graph about the different sexes for each news source. Ill wait to put that on the web once @jonhoranic is done messing with the css so there is no merge conflict.

**Comment by jonhoranic** [comment]
@ajnewton1 The CSS is proving a thorn in the side, I think we can iron it out as a team in class tomorrow now that I am messing with these "flex boxes". Do not worry about pushing things, get what you can in and I will keep trying what I can on my end. 

Since we need to develop some explanations, could you and @Samantha-Mcguigan gather some talking points on the articles you worked on, just so we can quickly develop and write them up. Taking the class time to push through the last bits should allow us to get this done.
